/* Automatically converted font */
    "MWRYSZR[QZRYR[ RRSQGRFSGRSRF", /* U+0 */
    "MaRYSZR[QZRYR[ RRSQGRFSGRSRF R\\Y]Z\\[[Z\\Y\\[ R\\S[G\\F]G\\S\\F",
    "MaRYSZR[QZRYR[ RRSQGRFSGRSRF RRYSZR[QZRYR[ RRSQGRFSGRSRF",
    "CaRFR[ RHFH[\\[\\F R\\[^[^`",
    "G]PFTFVGXIYMYTXXVZT[P[NZLXKTKMLINGPF RRATATF",

