# makefile.include for kbool
.cpp.o:
	g++ -c -Wall -O2 -I../include -o $@ $*.cpp

OBJECTS =\
    booleng.o\
    graph.o\
    graphlst.o\
    line.o\
    link.o\
    lpoint.o\
    node.o\
    record.o\
    scanbeam.o
