
MAKE = make -f makefile.gtk
KICAD_SUBDIRS =  common 3d-viewer eeschema eeschema/plugins pcbnew cvpcb kicad gerbview
KICAD_SUBDIRS_BIN =  eeschema eeschema/plugins pcbnew cvpcb kicad gerbview

all:
	@for dir in $(KICAD_SUBDIRS); do \
	  $(MAKE) -C $$dir; \
	done

install:
	@for dir in $(KICAD_SUBDIRS_BIN); do \
	  $(MAKE) -C $$dir install; \
	done
	
clean:
	@for dir in $(KICAD_SUBDIRS); do \
	  $(MAKE) -C $$dir clean; \
	done
