= KiCad GUI translations

This is the repository for the po files that is used for the GUI
translations for KiCad.

It is cmake equipped to conform with the rest of the installation
principles for KiCad.

== Depends
- Cmake
- Gettext

== How to install
```sh
$ cd kicad-i18n
$ BUILD_SRC=$(pwd)
$ mkdir -p ~/tmp/kicad-i18n-build
$ cd ~/tmp/kicad-i18n-build
$ cmake ${BUILD_SRC}
$ make install
$ cd ..
$ rm -rf ~/tmp/kicad-i18n-build
```

If you want to change the default install prefix to match your KiCad
build, you can add `cmake` option for example use:
```
-DCMAKE_INSTALL_PREFIX=/usr
```

If you occurred some problems, use `cmake --trace -DCMAKE_VERBOSE_MAKEFILE=ON` instead `cmake` to
make build log more verbose, when you fill issue report.

== Why are we not using transifex or similar service
We would like to make it easier for people to help translate, but I
don't really know how to make transifex work in synergy with a
workflow where people can also update by working with the po files
here directly.
