# File:		makefile for eeschema, mingw

#used only to define (KICAD_BIN) :
include ../../libs.win


all: netlist_form_pads-pcb.exe
			
netlist_form_pads-pcb.exe: netlist_form_pads-pcb.cpp
	gcc -Wall netlist_form_pads-pcb.cpp -o netlist_form_pads-pcb.exe
	
install:
	cp -v *.exe $(KICAD_BIN)/plugins/

clean :
	-$(RM) *.o
	-$(RM) *.exe
	-$(RM) *.bak

