# File:		makefile for kicad, wxGTK


include ../libs.linux

# Additional compiler flags
CPPFLAGS +=

FINAL = 1

TARGET = kicad

all: $(TARGET)

include makefile.include

CPPFLAGS += $(EXTRACPPFLAGS)
EDACPPFLAGS = $(CPPFLAGS)


$(TARGET): $(OBJECTS) makefile.gtk $(EXTRALIBS) ../libs.linux
	$(LD) $(OBJECTS) $(LDFLAGS)  $(LIBS) -o $(TARGET)

install:$(TARGET)
	cp -f  $(TARGET) $(KICAD_BIN)

clean:
	rm -f *.o;
	rm -f *~;
	rm -f core;
	rm -f *.bak
	rm -f $(TARGET)







