#define VAR                             1
#define ASSIGN                          2
#define SEMCOL                          3
#define PLUS                            4
#define MINUS                           5
#define UNIT                            6
#define DIVIDE                          7
#define MULT                            8
#define ENDS                            9
#define VALUE                          10
#define PARENL                         11
#define PARENR                         12
