#define VAR                             1
#define ASSIGN                          2
#define UNIT                            3
#define SEMCOL                          4
#define PLUS                            5
#define MINUS                           6
#define DIVIDE                          7
#define MULT                            8
#define ENDS                            9
#define VALUE                          10
#define PARENL                         11
#define PARENR                         12
