# File:		makefile

FINAL = 1


include ../libs.linux

# Compiler flags.
CPPFLAGS +=

EDACPPFLAGS = $(CPPFLAGS)

TARGET = cvpcb

all: $(TARGET)

include makefile.include

CPPFLAGS += $(EXTRACPPFLAGS)
EDACPPFLAGS = $(CPPFLAGS)


$(TARGET):	$(OBJECTS) makefile.gtk makefile.include $(EXTRALIBS) ../libs.linux $(LIBVIEWER3D)
	$(LD) $(OBJECTS) $(LDFLAGS)  $(LIBVIEWER3D)  $(LIBS_WITH_GL) -o $(TARGET)


install: $(TARGET)
	cp -f $(TARGET) $(KICAD_BIN)

clean:
		rm -f *.o
		rm -f $(TARGET)

