#ifndef __dialog_lib_edit_draw_item__
#define __dialog_lib_edit_draw_item__

/**
 * @file
 * Subclass of DIALOG_LIB_EDIT_DRAW_ITEM_BASE, which is generated by
 * wxFormBuilder.
 */

class LIB_DRAW_ITEM;


#include <dialog_lib_edit_draw_item_base.h>


/**
 * Dialog to edit library component graphic items.
 */
class DIALOG_LIB_EDIT_DRAW_ITEM : public DIALOG_LIB_EDIT_DRAW_ITEM_BASE
{
public:
    /** Constructor */
    DIALOG_LIB_EDIT_DRAW_ITEM( wxWindow* parent, const wxString& itemName );

    wxString GetWidth( void );
    void SetWidth( const wxString& width );

    bool GetApplyToAllConversions( void );
    void SetApplyToAllConversions( bool applyToAll );
    void EnableApplyToAllConversions( bool enable = true );

    bool GetApplyToAllUnits( void );
    void SetApplyToAllUnits( bool applyToAll );
    void EnableApplyToAllUnits( bool enable = true );

    int GetFillStyle( void );
    void SetFillStyle( int fillStyle );
    void EnableFillStyle( bool enable = true );

    void SetWidthUnits( const wxString& units );
};

#endif // __dialog_lib_edit_draw_item__
