#define G_IDENTIFIER                     1
#define G_ASSIGN                         2
#define G_SEMCOL                         3
#define G_BOOL_AND                       4
#define G_BOOL_OR                        5
#define G_BOOL_XOR                       6
#define G_LESS_THAN                      7
#define G_GREATER_THAN                   8
#define G_LESS_EQUAL_THAN                9
#define G_GREATER_EQUAL_THAN            10
#define G_EQUAL                         11
#define G_NOT_EQUAL                     12
#define G_BOOL_NOT                      13
#define G_PLUS                          14
#define G_MINUS                         15
#define G_DIVIDE                        16
#define G_MULT                          17
#define G_STRUCT_REF                    18
#define G_UNIT                          19
#define G_ENDS                          20
#define G_VALUE                         21
#define G_STRING                        22
#define G_PARENL                        23
#define G_PARENR                        24
