#include "bitmaps3d/import3d.xpm"

#include "bitmaps3d/rotate+x.xpm"
#include "bitmaps3d/rotate-x.xpm"
#include "bitmaps3d/rotate+y.xpm"
#include "bitmaps3d/rotate-y.xpm"
#include "bitmaps3d/rotate+z.xpm"
#include "bitmaps3d/rotate-z.xpm"
#include "bitmaps3d/axis3d.xpm"
#include "bitmaps3d/axis3d_bottom.xpm"
#include "bitmaps3d/axis3d_top.xpm"
#include "bitmaps3d/axis3d_left.xpm"
#include "bitmaps3d/axis3d_right.xpm"
#include "bitmaps3d/axis3d_front.xpm"
#include "bitmaps3d/axis3d_back.xpm"
