## Makefile for 3d-viewer.a ( wxMAC - mac os X)
CC = gcc

# Compiler flags.

CPPFLAGS =  -Wall -O2 -DPCBNEW  -I../pcbnew -I ../include -I../common\
	  `wx-config --cxxflags`
CPPFLAGS += -arch i386 -arch ppc


include ../libs.macosx

TARGET = 3d-viewer

FINAL = 1

all: $(TARGET).a

include makefile.include


$(TARGET).a: $(OBJECTS3D) makefile.gtk makefile.include
	rm -f $@
	ar -rv $@ $(OBJECTS3D)
	ranlib $@


clean:
		rm -f *.o
		rm -f *.exe
		rm -f *.res
		rm -f *.map
		rm -f $(TARGET).a



