## Makefile for 3d-viewer.a ( wxGTK - LINUX )

include ../libs.linux

# Compiler flags.
CPPFLAGS += -DPCBNEW -I../pcbnew -I ../include -I../common

TARGET = 3d-viewer

FINAL = 1

all: $(TARGET).a

include makefile.include


$(TARGET).a: $(OBJECTS3D) makefile.gtk makefile.include
	rm -f $@
	ar -rv $@ $(OBJECTS3D)
	ranlib $@

install:$(TARGET).a

clean:
	rm -f *.o
	rm -f *.exe
	rm -f *.res
	rm -f *.map
	rm -f $(TARGET).a



