## Makefile for 3d-viewer.a

include ../libs.macosx

TARGET = 3d-viewer.a

all: $(TARGET)

deps:
	$(CXX) $(CPPFLAGS) -E -MMD -MG *.cpp >/dev/null

include makefile.include
-include *.d

CPPFLAGS += -DPCBNEW  -I../pcbnew
EDACPPFLAGS = $(CPPFLAGS)

$(TARGET): $(OBJECTS3D) makefile.macosx makefile.include
	rm -f $@
	ar -rv $@ $(OBJECTS3D)
	ranlib $@


clean:
	rm -f *.o; rm -f *~
	rm -f $(TARGET)



