## Makefile for 3d-viewer.a

include ../libs.macosx

TARGET = 3d-viewer.a

all: $(TARGET)

include makefile.include

CPPFLAGS += -DPCBNEW  -I../pcbnew
EDACPPFLAGS = $(CPPFLAGS)

$(TARGET): $(OBJECTS3D) makefile.macosx makefile.include
	rm -f $@
	ar -rv $@ $(OBJECTS3D)
	ranlib $@


clean:
	rm -f *.o; rm -f *~
	rm -f $(TARGET)



