## Makefile for 3d-viewer.a ( wxGTK - LINUX )

include ../libs.linux

# Compiler flags.
CPPFLAGS += -DPCBNEW -I../pcbnew -I ../include -I../common

TARGET = 3d-viewer

FINAL = 1

all: $(TARGET).a

deps:
	$(CXX) $(CPPFLAGS) -E -MMD -MG *.cpp >/dev/null

include makefile.include
-include *.d

$(TARGET).a: $(OBJECTS3D) makefile.gtk makefile.include
	rm -f $@
	ar -rv $@ $(OBJECTS3D)
	ranlib $@

install:$(TARGET).a

clean:
	rm -f *.o *.exe *.res *.map *.d
	rm -f $(TARGET).a



