EXTRACPPFLAGS += -I$(SYSINCLUDE) -I./ -Ibitmaps -I../include

COMMON =



OBJECTS= \
		PolyLine.o\
		math_for_graphics.o\
        polygon_test_point_inside.o


PolyLine.o: PolyLine.cpp PolyLine.h

math_for_graphics.o: math_for_graphics.cpp math_for_graphics.h
