## Makefile for common.a
CC = gcc


include ../libs.linux

# Compiler flags.
CPPFLAGS +=  -I./ -I../include

EDACPPFLAGS = $(CPPFLAGS)

all: common.a

include makefile.include

CPPFLAGS += $(EXTRACPPFLAGS) -fno-strict-aliasing
EDACPPFLAGS = $(CPPFLAGS)


common.a: $(OBJECTS) makefile.gtk makefile.include
	rm -f $@
	ar -rv $@ $(OBJECTS)
	ranlib $@

install:common.a

clean:
	rm -f *.o
	rm -f *~
	rm -f core
	rm -f *.bak
	rm -f *.obj
	rm -f common.a


