WXDIR = $(WXWIN)

all: common.a

include ../libs.win

include makefile.include

all: common.a pcbcommon.a

common.a: $(COMMON_OBJECTS) ../libs.win makefile.include
	ar ruv $@ $(COMMON_OBJECTS)
	ranlib $@


pcbcommon.a: $(PCB_COMMON_OBJECTS) ../libs.win makefile.include
	ar ruv $@ $(PCB_COMMON_OBJECTS)
	ranlib $@


clean:
	rm -f *.bak
	rm -f *.o
	rm -f common.a
