## Makefile for common.a
CC = gcc


include ../libs.linux

all: common.a

deps:
	$(CXX) $(CPPFLAGS) -E -MMD -MG *.cpp >/dev/null

include makefile.include
-include *.d

# specfic Compiler flags and options
CPPFLAGS += $(EXTRACPPFLAGS) -I./ -I../include -I$(BOOST)
EDACPPFLAGS = $(CPPFLAGS)


common.a: $(OBJECTS) makefile.gtk makefile.include
	rm -f $@
	ar -rv $@ $(OBJECTS)
	ranlib $@

install:common.a

clean:
	rm -f *.o *~ core *.bak *.obj *.d
	rm -f common.a


