## Makefile for common.a

include ../libs.macosx

TARGET = common.a

all: $(TARGET)

deps:
	$(CXX) $(CPPFLAGS) -E -MMD -MG *.cpp >/dev/null

include makefile.include
-include *.d

CPPFLAGS += $(EXTRACPPFLAGS)
EDACPPFLAGS = $(CPPFLAGS)

$(TARGET): $(OBJECTS) makefile.macosx makefile.include
	rm -f $@
	ar -rv $@ $(OBJECTS)
	ranlib $@

clean:
	rm -f *.o; rm -f *~
	rm -f $(TARGET)
