## Makefile for common.a

include ../libs.macosx

TARGET = pcbnew

all: $(TARGET)

include makefile.include

CPPFLAGS += $(EXTRACPPFLAGS)
EDACPPFLAGS = $(CPPFLAGS)

$(TARGET): $(OBJECTS) makefile.macosx makefile.include
	rm -f $@
	ar -rv $@ $(OBJECTS)
	ranlib $@

clean:
	rm -f *.o; rm -f *~
	rm -f $(TARGET)
