#!/bin/sh
# RSS Feed Display Script by Hellf[i]re v0.1
#
# This script is designed for most any RSS Feed. As some feeds may
# not be
# completely compliant, it may need a bit of tweaking
#
# This script depends on curl.
# Gentoo: emerge -av net-misc/curl
# Debian: apt-get install curl
# Homepage: http://curl.haxx.se/
#
# Usage:
# .conkyrc: ${execi [time] /path/to/script/conky-rss.sh}
#
# Applications needed:
# bash, cat, grep, sed, curl
#
# Usage Example
# ${execi 300 /home/youruser/scripts/conky-rss.sh}

#RSS Setup
URI=http://sourceforge.net/export/rss2_keepsake.php?group_id=145591 #URI of RSS Feed
FEEDFILE="/tmp/kicad-svn-`date +%y%m%d-%H%M%S`.rss"
URLFILE="/tmp/kicad-svn-`date +%y%m%d-%H%M%S`.url"

# Get feed and save
EXEC="/usr/bin/curl -s" #Path to curl
`$EXEC $URI &> $FEEDFILE`

# Get commit description
cat $FEEDFILE                | \
grep title                   | \
sed -e 's/[ \t]*//'          | \
sed -e '/activity/d'         | \
sed -e '/artifact/d'         | \
sed -e 's/<title>//'         | \
sed -e 's/<\!\[CDATA\[//'    | \
sed -e 's/\]\]>//'           | \
sed -e 's/<\/title>//'

# Space between descriptions and messages
echo ""

# Get viewvc urls only
cat $FEEDFILE         | \
grep link             | \
sed -e '/tracker/d'   | \
sed -e '/export/d'    | \
sed -e 's/[ \t]*//'   | \
sed -e 's/<link>//'   | \
sed -e 's/<\/link>//' &> $URLFILE

# Get commit messages from urls
exec < $URLFILE
while read LINE
do
	curl -s "$LINE" | \
	grep vc_log  | \
	sed -e 's/<td><pre class=\"vc_log\">//' | \
	sed -e 's/<\/pre><\/td>//' | \
	sed -e '/<style/d'
done

rm /tmp/kicad-svn-*
