REM This file was created using <kicad_src>/scripts/library-repos-install.sh on linux.
REM Run it from a directory you desire as the base for all libraries.
git clone https://github.com/KiCad/kicad-library
git clone https://github.com/KiCad/Displays_7-Segment.pretty
git clone https://github.com/KiCad/Air_Coils_SML_NEOSID.pretty
git clone https://github.com/KiCad/Sockets_BNC.pretty
git clone https://github.com/KiCad/Buzzers_Beepers.pretty
git clone https://github.com/KiCad/Capacitors_Elko_ThroughHole.pretty
git clone https://github.com/KiCad/Capacitors.pretty
git clone https://github.com/KiCad/Capacitors_SMD.pretty
git clone https://github.com/KiCad/Capacitors_ThroughHole.pretty
git clone https://github.com/KiCad/Choke_Axial_ThroughHole.pretty
git clone https://github.com/KiCad/Choke_Radial_ThroughHole.pretty
git clone https://github.com/KiCad/Choke_SMD.pretty
git clone https://github.com/KiCad/Choke_Toroid_ThroughHole.pretty
git clone https://github.com/KiCad/Choke_Common-Mode_Wurth.pretty
git clone https://github.com/KiCad/Connect.pretty
git clone https://github.com/KiCad/Connectors_Serial_MOLEX.pretty
git clone https://github.com/KiCad/Converters_DCDC_ACDC.pretty
git clone https://github.com/KiCad/Crystals.pretty
git clone https://github.com/KiCad/Crystals_Oscillators_SMD.pretty
git clone https://github.com/KiCad/Diodes_SMD.pretty
git clone https://github.com/KiCad/Diodes_ThroughHole.pretty
git clone https://github.com/KiCad/Discret.pretty
git clone https://github.com/KiCad/Display.pretty
git clone https://github.com/KiCad/Divers.pretty
git clone https://github.com/KiCad/EuroBoard_Outline.pretty
git clone https://github.com/KiCad/Fiducials.pretty
git clone https://github.com/KiCad/Filters_HF_Coils_NEOSID.pretty
git clone https://github.com/KiCad/Footprint_Symbols.pretty
git clone https://github.com/KiCad/Fuse_Holders_and_Fuses.pretty
git clone https://github.com/KiCad/Heatsinks.pretty
git clone https://github.com/KiCad/Housings_ROHM.pretty
git clone https://github.com/KiCad/Housings_SIP9.pretty
git clone https://github.com/KiCad/Housings_SOT-23_SOT-143_TSOT-6.pretty
git clone https://github.com/KiCad/Housings_SOT-89.pretty
git clone https://github.com/KiCad/Housings_SOT.pretty
git clone https://github.com/KiCad/Housings_TO-50.pretty
git clone https://github.com/KiCad/Housings_TO-78.pretty
git clone https://github.com/KiCad/Housings_TO-92.pretty
git clone https://github.com/KiCad/Inductors.pretty
git clone https://github.com/KiCad/Inductors_NEOSID.pretty
git clone https://github.com/KiCad/IR-DirectFETs.pretty
git clone https://github.com/KiCad/Iut.pretty
git clone https://github.com/KiCad/Labels.pretty
git clone https://github.com/KiCad/LEDs.pretty
git clone https://github.com/KiCad/Hall-Effect_Transducers_LEM.pretty
git clone https://github.com/KiCad/Measurement_Points.pretty
git clone https://github.com/KiCad/Measurement_Scales.pretty
git clone https://github.com/KiCad/Mechanical_Sockets.pretty
git clone https://github.com/KiCad/Mounting_Holes.pretty
git clone https://github.com/KiCad/Muonde.pretty
git clone https://github.com/KiCad/NF-Transformers_ETAL.pretty
git clone https://github.com/KiCad/Oddities.pretty
git clone https://github.com/KiCad/Transistors_OldSowjetAera.pretty
git clone https://github.com/KiCad/Opto-Devices.pretty
git clone https://github.com/KiCad/Oscillator-Modules.pretty
git clone https://github.com/KiCad/Oscillators.pretty
git clone https://github.com/KiCad/Pentawatts.pretty
git clone https://github.com/KiCad/PFF_PSF_PSS_Leadforms.pretty
git clone https://github.com/KiCad/Pin_Arrays.pretty
git clone https://github.com/KiCad/Potentiometers.pretty
git clone https://github.com/KiCad/Power_Integrations.pretty
git clone https://github.com/KiCad/Printtrafo_CHK.pretty
git clone https://github.com/KiCad/Relays_ThroughHole.pretty
git clone https://github.com/KiCad/Resistors_SMD.pretty
git clone https://github.com/KiCad/Resistors_ThroughHole.pretty
git clone https://github.com/KiCad/Resistors_Universal.pretty
git clone https://github.com/KiCad/QFP.pretty
git clone https://github.com/KiCad/SMD_Packages.pretty
git clone https://github.com/KiCad/Sockets_DIP.pretty
git clone https://github.com/KiCad/Sockets_Mini-Universal.pretty
git clone https://github.com/KiCad/Sockets.pretty
git clone https://github.com/KiCad/Sockets_MOLEX_KK-System.pretty
git clone https://github.com/KiCad/Sockets_PGA.pretty
git clone https://github.com/KiCad/Sockets_WAGO734.pretty
git clone https://github.com/KiCad/SOIC_Packages.pretty
git clone https://github.com/KiCad/SSOP_Packages.pretty
git clone https://github.com/KiCad/Capacitors_Tantalum_SMD.pretty
git clone https://github.com/KiCad/Terminal_Blocks.pretty
git clone https://github.com/KiCad/Transformers_SMPS_ThroughHole.pretty
git clone https://github.com/KiCad/Transistors_SMD.pretty
git clone https://github.com/KiCad/Transistors_TO-220.pretty
git clone https://github.com/KiCad/Transistors_TO-247.pretty
git clone https://github.com/KiCad/Valves.pretty
git clone https://github.com/KiCad/Wire_Connections_Bridges.pretty
git clone https://github.com/KiCad/Wire_Pads.pretty
git clone https://github.com/KiCad/Pin_Headers.pretty
git clone https://github.com/KiCad/Socket_Strips.pretty
