/////////////////////////////////////////////////////////////////////////////
// Name:        essai.h
// Purpose:     
// Author:      jean-pierre Charras
// Modified by: 
// Created:     28/02/2006 07:46:42
// RCS-ID:      
// Copyright:   License GNU
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 28/02/2006 07:46:42

#ifndef _ESSAI_H_
#define _ESSAI_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "essai.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxFlexGridSizer;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10000
#define SYMBOL_ESSAI_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_ESSAI_TITLE _("essai")
#define SYMBOL_ESSAI_IDNAME ID_DIALOG
#define SYMBOL_ESSAI_SIZE wxSize(400, 300)
#define SYMBOL_ESSAI_POSITION wxDefaultPosition
#define ID_TEXTCTRL 10001
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * essai class declaration
 */

class essai: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( essai )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    essai( );
    essai( wxWindow* parent, wxWindowID id = SYMBOL_ESSAI_IDNAME, const wxString& caption = SYMBOL_ESSAI_TITLE, const wxPoint& pos = SYMBOL_ESSAI_POSITION, const wxSize& size = SYMBOL_ESSAI_SIZE, long style = SYMBOL_ESSAI_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ESSAI_IDNAME, const wxString& caption = SYMBOL_ESSAI_TITLE, const wxPoint& pos = SYMBOL_ESSAI_POSITION, const wxSize& size = SYMBOL_ESSAI_SIZE, long style = SYMBOL_ESSAI_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin essai event handler declarations

////@end essai event handler declarations

////@begin essai member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end essai member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin essai member variables
    wxFlexGridSizer* GridSizer;
////@end essai member variables
};

#endif
    // _ESSAI_H_
