/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright (C) 2018 Jean-Pierre Charras jp.charras at wanadoo.fr
 * Copyright The KiCad Developers, see AUTHORS.txt for contributors.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <board_connected_item.h>
#include <eda_shape.h>


class LINE_READER;
class EDA_DRAW_FRAME;
class FOOTPRINT;
class MSG_PANEL_ITEM;


class PCB_SHAPE : public BOARD_CONNECTED_ITEM, public EDA_SHAPE
{
public:
    PCB_SHAPE( BOARD_ITEM* aParent, KICAD_T aItemType, SHAPE_T aShapeType );

    PCB_SHAPE( BOARD_ITEM* aParent = nullptr, SHAPE_T aShapeType = SHAPE_T::SEGMENT );

    // Do not create a copy constructor & operator=.
    // The ones generated by the compiler are adequate.

    ~PCB_SHAPE() override;

    void CopyFrom( const BOARD_ITEM* aOther ) override;

    static bool ClassOf( const EDA_ITEM* aItem )
    {
        return aItem && PCB_SHAPE_T == aItem->Type();
    }

    wxString GetClass() const override
    {
        return wxT( "PCB_SHAPE" );
    }

    void Serialize( google::protobuf::Any &aContainer ) const override;
    bool Deserialize( const google::protobuf::Any &aContainer ) override;

    bool IsConnected() const override;

    wxString GetFriendlyName() const override { return getFriendlyName(); }

    bool IsType( const std::vector<KICAD_T>& aScanTypes ) const override;

    void SetLayer( PCB_LAYER_ID aLayer ) override;
    PCB_LAYER_ID GetLayer() const override { return m_layer; }

    bool IsOnLayer( PCB_LAYER_ID aLayer ) const override;

    virtual LSET GetLayerSet() const override;
    virtual void SetLayerSet( const LSET& aLayers ) override;

    void SetPosition( const VECTOR2I& aPos ) override { setPosition( aPos ); }
    VECTOR2I GetPosition() const override { return getPosition(); }

    VECTOR2I GetCenter() const override { return getCenter(); }

    void BeginEdit( const VECTOR2I& aStartPoint )
    {
        beginEdit( aStartPoint );
        syncLibCoords();
    }

    bool ContinueEdit( const VECTOR2I& aPosition )
    {
        bool result = continueEdit( aPosition );
        syncLibCoords();
        return result;
    }

    void CalcEdit( const VECTOR2I& aPosition )
    {
        calcEdit( aPosition );
        syncLibCoords();
    }

    void EndEdit( bool aClosed = true )
    {
        endEdit( aClosed );
        syncLibCoords();
    }

    void SetEditState( int aState ) { setEditState( aState ); }

    void SetArcAngleAndEnd( const EDA_ANGLE& aAngle, bool aCheckNegativeAngle = false )
    {
        EDA_SHAPE::SetArcAngleAndEnd( aAngle, aCheckNegativeAngle );
        syncLibCoords();
    }

    /**
     * @return a list of connection points (may be empty): points where this shape can form
     * electrical connections to other shapes that are natural "start/end" points.
     */
    std::vector<VECTOR2I> GetConnectionPoints() const;

    bool HasLineStroke() const override { return true; }

    STROKE_PARAMS GetStroke() const override;
    void          SetStroke( const STROKE_PARAMS& aStroke ) override;

    int GetWidth() const override;

    void StyleFromSettings( const BOARD_DESIGN_SETTINGS& settings, bool aCheckSide ) override;

    /**
     * Return 4 corners for a rectangle or rotated rectangle (stored as a poly).  Unimplemented
     * for other shapes.
     */
    virtual std::vector<VECTOR2I> GetCorners() const;

    /**
     * Allows items to return their visual center rather than their anchor. For some shapes this
     * is similar to GetCenter(), but for unfilled shapes a point on the outline is better.
     */
    const VECTOR2I GetFocusPosition() const override;

    /**
     * Make a set of SHAPE objects representing the PCB_SHAPE.  Caller owns the objects.
     */
    std::shared_ptr<SHAPE> GetEffectiveShape( PCB_LAYER_ID aLayer = UNDEFINED_LAYER,
                                              FLASHING aFlash = FLASHING::DEFAULT ) const override;

    bool IsProxyItem() const override { return m_proxyItem; }
    void SetIsProxyItem( bool aIsProxy = true ) override;

    void GetMsgPanelInfo( EDA_DRAW_FRAME* aFrame, std::vector<MSG_PANEL_ITEM>& aList ) override;

    const BOX2I GetBoundingBox() const override { return getBoundingBox(); }

    bool HitTest( const VECTOR2I& aPosition, int aAccuracy = 0 ) const override
    {
        return hitTest( aPosition, aAccuracy );
    }

    bool HitTest( const BOX2I& aRect, bool aContained, int aAccuracy = 0 ) const override
    {
        return hitTest( aRect, aContained, aAccuracy );
    }

    bool HitTest( const SHAPE_LINE_CHAIN& aPoly, bool aContained ) const override
    {
        return hitTest( aPoly, aContained );
    }

    void Normalize() override;

    /**
     * Normalize coordinates to compare 2 similar PCB_SHAPES
     * similat to Normalize(), but also normalize SEGMENT end points
     * needed only for graphic comparisons
     */
    void NormalizeForCompare() override;

    void Move( const VECTOR2I& aMoveVector ) override;

    void Rotate( const VECTOR2I& aRotCentre, const EDA_ANGLE& aAngle ) override;

    void Flip( const VECTOR2I& aCentre, FLIP_DIRECTION aFlipDirection ) override;

    void OnFootprintRescaled( double aRatioX, double aRatioY, double aLinearFactor, const VECTOR2I& aAnchor,
                              const EDA_ANGLE& aParentRotate ) override;

    void OnFootprintTransformed() override { RebakeFromLib(); }

    virtual void Mirror( const VECTOR2I& aCentre, FLIP_DIRECTION aFlipDirection ) override;

    void SetStart( const VECTOR2I& aStart ) override;
    void SetEnd( const VECTOR2I& aEnd ) override;

    // Stroke width is stored in lib units. Scale-aware accessors apply the
    // parent footprint scale on read / strip it on write so callers see the
    // runtime width as before.
    void SetWidth( int aWidth ) override;

    void SetShape( SHAPE_T aShape ) override
    {
        EDA_SHAPE::SetShape( aShape );
        m_libShape = aShape;
    }

    void SetArcGeometry( const VECTOR2I& aStart, const VECTOR2I& aMid, const VECTOR2I& aEnd );

    void SetBezierC1( const VECTOR2I& aPt ) override;
    void SetBezierC2( const VECTOR2I& aPt ) override;

    void SetPolyShape( const SHAPE_POLY_SET& aShape ) override;

    void SetEllipseCenter( const VECTOR2I& aPt ) override;
    void SetEllipseMajorRadius( int aR ) override;
    void SetEllipseMinorRadius( int aR ) override;
    void SetEllipseRotation( const EDA_ANGLE& aA ) override;
    void SetEllipseStartAngle( const EDA_ANGLE& aA ) override;
    void SetEllipseEndAngle( const EDA_ANGLE& aA ) override;

    VECTOR2I GetLibraryStart() const { return m_libStart; }
    VECTOR2I GetLibraryEnd() const { return m_libEnd; }
    SHAPE_T  GetLibraryShape() const { return m_libShape; }

    VECTOR2I  GetLibraryEllipseCenter() const      { return m_libEllipseCenter; }
    int       GetLibraryEllipseMajorRadius() const { return m_libEllipseMajorRadius; }
    int       GetLibraryEllipseMinorRadius() const { return m_libEllipseMinorRadius; }
    EDA_ANGLE GetLibraryEllipseRotation() const    { return m_libEllipseRotation; }
    EDA_ANGLE GetLibraryEllipseStartAngle() const  { return m_libEllipseStartAngle; }
    EDA_ANGLE GetLibraryEllipseEndAngle() const    { return m_libEllipseEndAngle; }

    void SetLibraryEllipse( const VECTOR2I& aCenter, int aMajor, int aMinor, const EDA_ANGLE& aRotation,
                            const EDA_ANGLE& aStartAngle, const EDA_ANGLE& aEndAngle )
    {
        m_libEllipseCenter = aCenter;
        m_libEllipseMajorRadius = aMajor;
        m_libEllipseMinorRadius = aMinor;
        m_libEllipseRotation = aRotation;
        m_libEllipseStartAngle = aStartAngle;
        m_libEllipseEndAngle = aEndAngle;

        EDA_SHAPE::SetEllipseCenter( aCenter );
        EDA_SHAPE::SetEllipseMajorRadius( aMajor );
        EDA_SHAPE::SetEllipseMinorRadius( aMinor );
        EDA_SHAPE::SetEllipseRotation( aRotation );
        EDA_SHAPE::SetEllipseStartAngle( aStartAngle );
        EDA_SHAPE::SetEllipseEndAngle( aEndAngle );
    }

    VECTOR2I       GetLibraryArcMid() const;
    VECTOR2I       GetLibraryBezierC1() const;
    VECTOR2I       GetLibraryBezierC2() const;
    SHAPE_POLY_SET GetLibraryPolyShape() const;

    void RebakeFromLib();

    void OverrideLibCoords( const VECTOR2I& aStart, const VECTOR2I& aEnd, const VECTOR2I& aArcMid = VECTOR2I( 0, 0 ) )
    {
        m_libStart = aStart;
        m_libEnd = aEnd;

        if( m_libShape == SHAPE_T::ARC )
            m_libArcMid = aArcMid;
    }

    void OverrideLibBezier( const VECTOR2I& aC1, const VECTOR2I& aC2 )
    {
        m_libBezierC1 = aC1;
        m_libBezierC2 = aC2;
    }

    void OverrideLibPoly( const SHAPE_POLY_SET& aPoly ) { m_libPoly = aPoly; }

    const SHAPE_POLY_SET& GetLibPoly() const { return m_libPoly; }

    void Scale( double aScale );

    void UpdateHatching() const override;

    /**
     * Convert the shape to a closed polygon.  Circles and arcs are approximated by segments.
     *
     * @param aBuffer is a buffer to store the polygon.
     * @param aClearance is the clearance around the pad.
     * @param aError is the maximum deviation from a true arc.
     * @param aErrorLoc whether any approximation error should be placed inside or outside
     * @param ignoreLineWidth is used for edge cut items where the line width is only for
     *                        visualization
     */
    void TransformShapeToPolygon( SHAPE_POLY_SET& aBuffer, PCB_LAYER_ID aLayer, int aClearance,
                                  int aError, ERROR_LOC aErrorLoc,
                                  bool ignoreLineWidth = false ) const override;

    /**
     * Convert the item shape to a polyset. Circles and arcs are approximated by segments; hatched
     * fills and details (if any) will be included.
     *
     * @param aBuffer a buffer to store the polygon.
     * @param aClearance the clearance around the pad.
     * @param aError the maximum deviation from true circle.
     * @param aErrorLoc should the approximation error be placed outside or inside the polygon?
     * @param aRenderSettings used to plot outlines with not solid segments like dashed lines.
     * So it is not used by all BOARD_ITEMS. If null lines like dashed will be converted as SOLID
     */
    void TransformShapeToPolySet( SHAPE_POLY_SET& aBuffer, PCB_LAYER_ID aLayer,
                                  int aClearance, int aError, ERROR_LOC aErrorLoc,
                                  KIGFX::RENDER_SETTINGS* aRenderSettings = nullptr ) const override;

    wxString GetItemDescription( UNITS_PROVIDER* aUnitsProvider, bool aFull ) const override;

    BITMAPS GetMenuImage() const override;

    EDA_ITEM* Clone() const override;

    const BOX2I ViewBBox() const override;

    std::vector<int> ViewGetLayers() const override;

    ///< @copydoc VIEW_ITEM::ViewGetLOD
    double ViewGetLOD( int aLayer, const KIGFX::VIEW* aView ) const override;

    double Similarity( const BOARD_ITEM& aBoardItem ) const override;

    bool operator==( const PCB_SHAPE& aShape ) const;
    bool operator==( const BOARD_ITEM& aBoardItem ) const override;

    void SetHasSolderMask( bool aVal ) { m_hasSolderMask = aVal; }
    bool HasSolderMask() const         { return m_hasSolderMask; }

    void SetLocalSolderMaskMargin( std::optional<int> aMargin ) { m_solderMaskMargin = aMargin; }
    std::optional<int> GetLocalSolderMaskMargin() const         { return m_solderMaskMargin; }

    int GetSolderMaskExpansion() const;

#if defined(DEBUG)
    void Show( int nestLevel, std::ostream& os ) const override { ShowDummy( os ); }
#endif

protected:
    void swapData( BOARD_ITEM* aImage ) override;

    bool isMoving() const override { return IsMoving(); }

    void syncLibCoords();

    // Returns the parent footprint to use for lib/board frame conversion. Pad primitives
    // are stored pad-local so they get nullptr (the pad applies its own transform when
    // building the effective shape).
    const FOOTPRINT* transformFp() const;

    int getMaxError() const override;

    SHAPE_POLY_SET getHatchingKnockouts() const override;

    struct cmp_drawings
    {
        bool operator()( const BOARD_ITEM* aFirst, const BOARD_ITEM* aSecond ) const;
    };

protected:
    bool               m_hasSolderMask;
    std::optional<int> m_solderMaskMargin;

    VECTOR2I m_libStart;
    VECTOR2I m_libEnd;

    VECTOR2I m_libArcMid;

    VECTOR2I m_libBezierC1;
    VECTOR2I m_libBezierC2;

    SHAPE_POLY_SET m_libPoly;

    VECTOR2I  m_libEllipseCenter;
    int       m_libEllipseMajorRadius;
    int       m_libEllipseMinorRadius;
    EDA_ANGLE m_libEllipseRotation;
    EDA_ANGLE m_libEllipseStartAngle;
    EDA_ANGLE m_libEllipseEndAngle;

    SHAPE_T m_libShape;
};
