/////////////////////////////////////////////////////////////////////////////
// Name:        set_grid.h
// Purpose:     
// Author:      jean-pierre Charras
// Modified by: 
// Created:     26/02/2006 17:24:12
// RCS-ID:      
// Copyright:   License GNU
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 26/02/2006 17:24:12

#ifndef _SET_GRID_H_
#define _SET_GRID_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10000
#define SYMBOL_WINEDA_PCBGRIDFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_WINEDA_PCBGRIDFRAME_TITLE _("User Grid Size")
#define SYMBOL_WINEDA_PCBGRIDFRAME_IDNAME ID_DIALOG
#define SYMBOL_WINEDA_PCBGRIDFRAME_SIZE wxSize(400, 300)
#define SYMBOL_WINEDA_PCBGRIDFRAME_POSITION wxDefaultPosition
#define ID_RADIOBOX 10001
#define ID_TEXTCTRL 10002
#define ID_TEXTCTRL1 10003
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * WinEDA_PcbGridFrame class declaration
 */

class WinEDA_PcbGridFrame: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( WinEDA_PcbGridFrame )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    WinEDA_PcbGridFrame( );
    WinEDA_PcbGridFrame( WinEDA_BasePcbFrame* parent,
		const wxPoint& pos = SYMBOL_WINEDA_PCBGRIDFRAME_POSITION,
		wxWindowID id = SYMBOL_WINEDA_PCBGRIDFRAME_IDNAME, const wxString& caption = SYMBOL_WINEDA_PCBGRIDFRAME_TITLE, const wxSize& size = SYMBOL_WINEDA_PCBGRIDFRAME_SIZE, long style = SYMBOL_WINEDA_PCBGRIDFRAME_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WINEDA_PCBGRIDFRAME_IDNAME, const wxString& caption = SYMBOL_WINEDA_PCBGRIDFRAME_TITLE, const wxPoint& pos = SYMBOL_WINEDA_PCBGRIDFRAME_POSITION, const wxSize& size = SYMBOL_WINEDA_PCBGRIDFRAME_SIZE, long style = SYMBOL_WINEDA_PCBGRIDFRAME_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin WinEDA_PcbGridFrame event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_OK
    void OnOkClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_CANCEL
    void OnCancelClick( wxCommandEvent& event );

////@end WinEDA_PcbGridFrame event handler declarations

////@begin WinEDA_PcbGridFrame member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end WinEDA_PcbGridFrame member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();
	void AcceptPcbOptions(wxCommandEvent& event);

////@begin WinEDA_PcbGridFrame member variables
    wxRadioBox* m_UnitGrid;
    wxTextCtrl* m_OptGridSizeX;
    wxTextCtrl* m_OptGridSizeY;
////@end WinEDA_PcbGridFrame member variables
	WinEDA_BasePcbFrame * m_Parent;
};

#endif
    // _SET_GRID_H_
