
// Largeur du toolbar vertical
#define VTOOLBAR_WIDTH 26
// dimension d'un tool vertical
#define TOOL_SIZE 23

	/****************************/
	/* Used bitmaps in Kicad */
	/****************************/

	#include "../bitmaps/Cancel.xpm"
	#include "../bitmaps/cancel_tool.xpm"
	#include "../bitmaps/Apply.xpm"
	#include "../bitmaps/reload2.xpm"

	#include "../bitmaps/icon_txt.xpm"
	#include "../bitmaps/new_txt.xpm"
	#include "../bitmaps/directory.xpm"
	#include "../bitmaps/icon_python_small.xpm"
	#include "../bitmaps/Web_support.xpm"

	#include "../bitmaps/Fonts.xpm"

	#include "../bitmaps/save.xpm"
	#include "../bitmaps/save_as.xpm"
	#include "../bitmaps/Save_Project.xpm"
	#include "../bitmaps/Save_CmpStuff.xpm"
	#include "../bitmaps/Save_NetList.xpm"
	#include "../bitmaps/Save_SetUp.xpm"
	#include "../bitmaps/Read_SetUp.xpm"
	#include "../bitmaps/Editor.xpm"

	#include "../bitmaps/Open_Library.xpm"
	#include "../bitmaps/New_Library.xpm"
	#include "../bitmaps/Save_Library.xpm"

	#include "../bitmaps/Edit.xpm"
	#include "../bitmaps/Edit_Text.xpm"

	#include "../bitmaps/plot.xpm"
	#include "../bitmaps/plot_PS.xpm"
	#include "../bitmaps/plot_HPG.xpm"

	#include "../bitmaps/Add_Zone.xpm"
	#include "../bitmaps/Add_Zone_Cutout.xpm"
	#include "../bitmaps/Add_Corner.xpm"
	#include "../bitmaps/Add_Circle.xpm"
	#include "../bitmaps/Add_Line.xpm"
	#include "../bitmaps/Add_Arc.xpm"
	#include "../bitmaps/Add_Dashed_Line.xpm"
	#include "../bitmaps/Add_Entry.xpm"
	#include "../bitmaps/Add_Polygon.xpm"
	#include "../bitmaps/Add_Rectangle.xpm"
	#include "../bitmaps/Add_Text.xpm"
	#include "../bitmaps/Add_Line_Label.xpm"
	#include "../bitmaps/Add_GLabel.xpm"
	#include "../bitmaps/Add_Junction.xpm"

	#include "../bitmaps/Add_Power.xpm"
	#include "../bitmaps/Add_Bus2Bus.xpm"
	#include "../bitmaps/Add_Line2Bus.xpm"
	#include "../bitmaps/add_bus.xpm"
	#include "../bitmaps/add_hierarchical_label.xpm"
	#include "../bitmaps/add_hierar_pin.xpm"
	#include "../bitmaps/add_hierar_subsheet.xpm"
	#include "../bitmaps/import_hierarchical_label.xpm"

	#include "../bitmaps/general_deletions.xpm"
	#include "../bitmaps/Delete_Text.xpm"
	#include "../bitmaps/Delete_Cotation.xpm"
	#include "../bitmaps/Delete_Arc.xpm"
	#include "../bitmaps/Delete_Circle.xpm"
	#include "../bitmaps/Delete_Field.xpm"
	#include "../bitmaps/Delete_Line.xpm"
	#include "../bitmaps/Delete_Segment.xpm"
	#include "../bitmaps/Delete_Polygon.xpm"
	#include "../bitmaps/Delete_Rectangle.xpm"

	#include "../bitmaps/Move.xpm"
	#include "../bitmaps/Move_Text.xpm"
	#include "../bitmaps/Move_Arc.xpm"
	#include "../bitmaps/Move_Circle.xpm"
	#include "../bitmaps/Move_Field.xpm"
	#include "../bitmaps/Move_Line.xpm"
	#include "../bitmaps/Move_Polygon.xpm"
	#include "../bitmaps/Move_Rectangle.xpm"

	#include "../bitmaps/Options_Text.xpm"
	#include "../bitmaps/Options_Arc.xpm"
	#include "../bitmaps/Options_Circle.xpm"
	#include "../bitmaps/Options_Segment.xpm"
	#include "../bitmaps/Options_Rectangle.xpm"
	#include "../bitmaps/Display_Options.xpm"
	#include "../bitmaps/opt_show_polygon.xpm"

	#include "../bitmaps/Mirror_V.xpm"
	#include "../bitmaps/Mirror_H.xpm"
	#include "../bitmaps/Orient.xpm"
	#include "../bitmaps/Rotate+.xpm"
	#include "../bitmaps/Rotate-.xpm"
	#include "../bitmaps/Rotate_Field.xpm"
	#include "../bitmaps/Exit.xpm"
	#include "../bitmaps/Datasheet.xpm"
	#include "../bitmaps/CopyBlock.xpm"
	#include "../bitmaps/new.xpm"
	#include "../bitmaps/open.xpm"
	#include "../bitmaps/polar.xpm"
	#include "../bitmaps/copy.xpm"
	#include "../bitmaps/cut.xpm"
	#include "../bitmaps/paste.xpm"
	#include "../bitmaps/print.xpm"
	#include "../bitmaps/find.xpm"
	#include "../bitmaps/Cursor_Shape.xpm"
	#include "../bitmaps/Add_Component.xpm"
	#include "../bitmaps/noconn.xpm"

	#include "../bitmaps/zoom.xpm"
	#include "../bitmaps/Zoom_Center.xpm"
	#include "../bitmaps/Zoom_Out.xpm"
	#include "../bitmaps/Zoom_In.xpm"
	#include "../bitmaps/Zoom_Optimal.xpm"
	#include "../bitmaps/Zoom_Select.xpm"
	#include "../bitmaps/Zoom_Selected.xpm"
	#include "../bitmaps/Repaint.xpm"

	#include "../bitmaps/left.xpm"
	#include "../bitmaps/right.xpm"
	#include "../bitmaps/up.xpm"
	#include "../bitmaps/down.xpm"

	#include "../bitmaps/File_FootPrint.xpm"
	#include "../bitmaps/Footprint_Text.xpm"

	#include "../bitmaps/Options_Pad.xpm"
	#include "../bitmaps/Options_New_Pad.xpm"

	#include "../bitmaps/sheetset.xpm"
	#include "../bitmaps/library.xpm"
	#include "../bitmaps/dashline.xpm"
	#include "../bitmaps/annotate.xpm"
	#include "../bitmaps/netlist.xpm"
	#include "../bitmaps/erc.xpm"
	#include "../bitmaps/tools.xpm"
	#include "../bitmaps/libview.xpm"
	#include "../bitmaps/libedprt.xpm"
	#include "../bitmaps/export.xpm"
	#include "../bitmaps/import.xpm"
	#include "../bitmaps/delete.xpm"
	#include "../bitmaps/schematic.xpm"
	#include "../bitmaps/pin.xpm"
	#include "../bitmaps/Morgan1.xpm"
	#include "../bitmaps/Morgan2.xpm"
	#include "../bitmaps/anchor.xpm"
	#include "../bitmaps/del_body.xpm"
	#include "../bitmaps/libsavem.xpm"
	#include "../bitmaps/label.xpm"
	#include "../bitmaps/undelete.xpm"
	#include "../bitmaps/undo.xpm"
	#include "../bitmaps/redo.xpm"
	#include "../bitmaps/eeschema.xpm"
	#include "../bitmaps/pcbnew.xpm"
	#include "../bitmaps/treensel.xpm"
	#include "../bitmaps/book.xpm"
	#include "../bitmaps/module.xpm"
	#include "../bitmaps/modedit.xpm"
	#include "../bitmaps/config.xpm"
	#include "../bitmaps/auto_associe.xpm"
	#include "../bitmaps/icon_cvpcb.xpm"
	#include "../bitmaps/icon_eeschema.xpm"
	#include "../bitmaps/icon_gerbview.xpm"
	#include "../bitmaps/icon_kicad.xpm"
	#include "../bitmaps/icon_pcbnew.xpm"
	#include "../bitmaps/icon_modedit.xpm"
	#include "../bitmaps/Info.xpm"
	#include "../bitmaps/icon_python.xpm"
	#include "../bitmaps/mirepcb.xpm"
	#include "../bitmaps/icon_3d.xpm"
	#include "../bitmaps/drc_off.xpm"
	#include "../bitmaps/grid.xpm"
	#include "../bitmaps/grid_select.xpm"
	#include "../bitmaps/unit_mm.xpm"
	#include "../bitmaps/unit_inch.xpm"
	#include "../bitmaps/cursor.xpm"
	#include "../bitmaps/ratsnest.xpm"
	#include "../bitmaps/modratsnest.xpm"
	#include "../bitmaps/del_track.xpm"
	#include "../bitmaps/pad.xpm"
	#include "../bitmaps/Pad_Sketch.xpm"
	#include "../bitmaps/Text_Sketch.xpm"
	#include "../bitmaps/showtrack.xpm"
	#include "../bitmaps/showmodedge.xpm"
	#include "../bitmaps/showdcode.xpm"
	#include "../bitmaps/palette.xpm"
	#include "../bitmaps/help.xpm"
	#include "../bitmaps/green.xpm"
	#include "../bitmaps/red.xpm"
	#include "../bitmaps/preference.xpm"
	#include "../bitmaps/3d.xpm"
	#include "../bitmaps/hammer.xpm"
	#include "../bitmaps/jigsaw.xpm"
	#include "../bitmaps/library_update.xpm"
	#include "../bitmaps/transistor.xpm"
	#include "../bitmaps/kicad_icon_small.xpm"
	#include "../bitmaps/general_ratsnet.xpm"
	#include "../bitmaps/Add_Tracks.xpm"
	#include "../bitmaps/Auto_track_width.xpm"
	#include "../bitmaps/fill_zone.xpm"
	#include "../bitmaps/Width_Segment.xpm"
    
	#include "../bitmaps/annotate_right_down.xpm"
	#include "../bitmaps/annotate_down_right.xpm"

	#include "../bitmaps/new_sch.xpm"
	#include "../bitmaps/Open_Project.xpm"
	#include "../bitmaps/new_cvpcb.xpm"
	#include "../bitmaps/zip.xpm"
	#include "../bitmaps/icon_gerbview_small.xpm"
	#include "../bitmaps/zip_tool.xpm"
	#include "../bitmaps/unzip.xpm"
	#include "../bitmaps/Browse_Files.xpm"
	#include "../bitmaps/New_Project.xpm"
	#include "../bitmaps/new_gerb.xpm"
	#include "../bitmaps/new_python.xpm"
	#include "../bitmaps/icon_cvpcb_small.xpm"
	#include "../bitmaps/unknown.xpm"
	#include "../bitmaps/new_pcb.xpm"

	#include "../bitmaps/reload.xpm"

	#include "../bitmaps/treesel.xpm"
	#include "../bitmaps/ercerr.xpm"
	#include "../bitmaps/ercwarn.xpm"

	#include "../bitmaps/add_cotation.xpm"
	#include "../bitmaps/Add_Mires.xpm"
	#include "../bitmaps/Break_Line.xpm"
	#include "../bitmaps/Delete_Module.xpm"
	#include "../bitmaps/Delete_Net.xpm"
	#include "../bitmaps/Delete_Node.xpm"
	#include "../bitmaps/Delete_Pad.xpm"
	#include "../bitmaps/Delete_Track.xpm"
	#include "../bitmaps/Drag_Module.xpm"
	#include "../bitmaps/Drag_Outline_Segment.xpm"
	#include "../bitmaps/Drag_Pad.xpm"
	#include "../bitmaps/Drag_Segment_WithSlope.xpm"
	#include "../bitmaps/Drag_Track_Segment.xpm"
	#include "../bitmaps/Edges_Sketch.xpm"
	#include "../bitmaps/Edit_Module.xpm"
	#include "../bitmaps/Export_Module.xpm"
	#include "../bitmaps/Export_Options_Pad.xpm"
	#include "../bitmaps/Flag.xpm"
	#include "../bitmaps/Global_Options_Pad.xpm"
	#include "../bitmaps/Import_Module.xpm"
	#include "../bitmaps/Insert_Module_Board.xpm"
	#include "../bitmaps/Invert_Module.xpm"
	#include "../bitmaps/Load_Module_Board.xpm"
	#include "../bitmaps/Load_Module_Lib.xpm"
	#include "../bitmaps/local_ratsnet.xpm"
	#include "../bitmaps/Locked.xpm"
	#include "../bitmaps/Mode_Module.xpm"
	#include "../bitmaps/Mode_Track.xpm"
	#include "../bitmaps/Module_Check.xpm"
	#include "../bitmaps/Modul_Edit.xpm"
	#include "../bitmaps/module_options.xpm"
	#include "../bitmaps/Module_Ratsnet.xpm"
	#include "../bitmaps/Move_Module.xpm"
	#include "../bitmaps/Move_Pad.xpm"
	#include "../bitmaps/Move_Pin.xpm"
	#include "../bitmaps/Move_Track_Segment.xpm"
	#include "../bitmaps/Move_Track.xpm"
	#include "../bitmaps/mw_Add_Gap.xpm"
	#include "../bitmaps/mw_Add_Line.xpm"
	#include "../bitmaps/mw_Add_Shape.xpm"
	#include "../bitmaps/mw_Add_stub_arc.xpm"
	#include "../bitmaps/mw_Add_Stub.xpm"
	#include "../bitmaps/mw_toolbar.xpm"
	#include "../bitmaps/Net_HighLight.xpm"
	#include "../bitmaps/net_hightlight.xpm"
	#include "../bitmaps/Net_Locked.xpm"
	#include "../bitmaps/Net_UnLocked.xpm"
	#include "../bitmaps/New_FootPrint.xpm"
	#include "../bitmaps/New_Module.xpm"
	#include "../bitmaps/Options_All_Tracks&Vias.xpm"
	#include "../bitmaps/Options_All_Tracks.xpm"
	#include "../bitmaps/Options_All_Vias.xpm"
	#include "../bitmaps/Options_Module.xpm"
	#include "../bitmaps/Options_Tracks.xpm"
	#include "../bitmaps/Options_Track.xpm"
	#include "../bitmaps/Options_Vias.xpm"
	#include "../bitmaps/PcbOffset.xpm"
	#include "../bitmaps/Post_Compo.xpm"
	#include "../bitmaps/Post_Drill.xpm"
	#include "../bitmaps/Post_Module.xpm"
	#include "../bitmaps/Rotate_Module-.xpm"
	#include "../bitmaps/Rotate_Module+.xpm"
	#include "../bitmaps/Select_Layer_Pair.xpm"
	#include "../bitmaps/Select_W_Layer.xpm"
	#include "../bitmaps/Show_Zone.xpm"
	#include "../bitmaps/Swap_Layer.xpm"
	#include "../bitmaps/tool_ratsnet.xpm"
	#include "../bitmaps/Track_Locked.xpm"
	#include "../bitmaps/Track_Sketch.xpm"
	#include "../bitmaps/Track_UnLocked.xpm"
	#include "../bitmaps/Unlocked.xpm"
	#include "../bitmaps/Update_Module_Board.xpm"
	#include "../bitmaps/Width_Net.xpm"
	#include "../bitmaps/Width_Track_Via.xpm"
	#include "../bitmaps/Width_Track.xpm"
	#include "../bitmaps/Width_Vias.xpm"
