// Do not edit this file, it is autogenerated by CMake from the .md file
_HKI( "### Bridged Tee Attenuator\n"
"__Zin__ desired input impedance in &#x2126;<br>\n"
"__Zout__ desired output impedance<br>\n"
"__Z<sub>0</sub> = Zin = Zout__<br><br>\n"
"\n"
"* __a__ attenuation in dB\n"
"* __L = 10<sup>a/20</sup>__ (the loss)<br><br>\n"
"* ___R1 = Z<sub>0</sub> \\* (L - 1)___\n"
"* ___R2 = Z<sub>0</sub> / (L - 1)___" );
